[GLOBAL]
pants_version = "2.6.1rc2"
backend_packages = [
  'pants.backend.python',
  'pants.backend.python.lint.isort',
  'pants.backend.python.lint.black',
  'pants.backend.python.lint.flake8',
  'pants.backend.python.typecheck.mypy'
]

[source]
root_patterns = ['src/']

[python-setup]
interpreter_constraints = ['>=3.8']

[flake8]
config = 'setup.cfg'

[anonymous-telemetry]
enabled = true
repo_id = "2c4ccb62-4dfa-11ec-81d3-0242ac130003" 